# 1 "led/led.c"
# 1 "/home/y/y-c-msp430/fr6989/2-led-test//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "led/led.c"


# 1 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430.h" 1 3 4
# 1678 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430.h" 3 4
# 1 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 1 3 4
# 68 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
# 1 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/iomacros.h" 1 3 4
# 69 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 2 3 4
# 123 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
# 1 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/in430.h" 1 3 4
# 48 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/in430.h" 3 4

# 48 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/in430.h" 3 4
typedef unsigned int __istate_t;
# 124 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 2 3 4
# 148 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int ADC12CTL0;
extern volatile unsigned char ADC12CTL0_L;
extern volatile unsigned char ADC12CTL0_H;
extern volatile unsigned int ADC12CTL1;
extern volatile unsigned char ADC12CTL1_L;
extern volatile unsigned char ADC12CTL1_H;
extern volatile unsigned int ADC12CTL2;
extern volatile unsigned char ADC12CTL2_L;
extern volatile unsigned char ADC12CTL2_H;
extern volatile unsigned int ADC12CTL3;
extern volatile unsigned char ADC12CTL3_L;
extern volatile unsigned char ADC12CTL3_H;
extern volatile unsigned int ADC12LO;
extern volatile unsigned char ADC12LO_L;
extern volatile unsigned char ADC12LO_H;
extern volatile unsigned int ADC12HI;
extern volatile unsigned char ADC12HI_L;
extern volatile unsigned char ADC12HI_H;
extern volatile unsigned int ADC12IFGR0;
extern volatile unsigned char ADC12IFGR0_L;
extern volatile unsigned char ADC12IFGR0_H;
extern volatile unsigned int ADC12IFGR1;
extern volatile unsigned char ADC12IFGR1_L;
extern volatile unsigned char ADC12IFGR1_H;
extern volatile unsigned int ADC12IFGR2;
extern volatile unsigned char ADC12IFGR2_L;
extern volatile unsigned char ADC12IFGR2_H;
extern volatile unsigned int ADC12IER0;
extern volatile unsigned char ADC12IER0_L;
extern volatile unsigned char ADC12IER0_H;
extern volatile unsigned int ADC12IER1;
extern volatile unsigned char ADC12IER1_L;
extern volatile unsigned char ADC12IER1_H;
extern volatile unsigned int ADC12IER2;
extern volatile unsigned char ADC12IER2_L;
extern volatile unsigned char ADC12IER2_H;
extern volatile unsigned int ADC12IV;
extern volatile unsigned char ADC12IV_L;
extern volatile unsigned char ADC12IV_H;

extern volatile unsigned int ADC12MCTL0;
extern volatile unsigned char ADC12MCTL0_L;
extern volatile unsigned char ADC12MCTL0_H;
extern volatile unsigned int ADC12MCTL1;
extern volatile unsigned char ADC12MCTL1_L;
extern volatile unsigned char ADC12MCTL1_H;
extern volatile unsigned int ADC12MCTL2;
extern volatile unsigned char ADC12MCTL2_L;
extern volatile unsigned char ADC12MCTL2_H;
extern volatile unsigned int ADC12MCTL3;
extern volatile unsigned char ADC12MCTL3_L;
extern volatile unsigned char ADC12MCTL3_H;
extern volatile unsigned int ADC12MCTL4;
extern volatile unsigned char ADC12MCTL4_L;
extern volatile unsigned char ADC12MCTL4_H;
extern volatile unsigned int ADC12MCTL5;
extern volatile unsigned char ADC12MCTL5_L;
extern volatile unsigned char ADC12MCTL5_H;
extern volatile unsigned int ADC12MCTL6;
extern volatile unsigned char ADC12MCTL6_L;
extern volatile unsigned char ADC12MCTL6_H;
extern volatile unsigned int ADC12MCTL7;
extern volatile unsigned char ADC12MCTL7_L;
extern volatile unsigned char ADC12MCTL7_H;
extern volatile unsigned int ADC12MCTL8;
extern volatile unsigned char ADC12MCTL8_L;
extern volatile unsigned char ADC12MCTL8_H;
extern volatile unsigned int ADC12MCTL9;
extern volatile unsigned char ADC12MCTL9_L;
extern volatile unsigned char ADC12MCTL9_H;
extern volatile unsigned int ADC12MCTL10;
extern volatile unsigned char ADC12MCTL10_L;
extern volatile unsigned char ADC12MCTL10_H;
extern volatile unsigned int ADC12MCTL11;
extern volatile unsigned char ADC12MCTL11_L;
extern volatile unsigned char ADC12MCTL11_H;
extern volatile unsigned int ADC12MCTL12;
extern volatile unsigned char ADC12MCTL12_L;
extern volatile unsigned char ADC12MCTL12_H;
extern volatile unsigned int ADC12MCTL13;
extern volatile unsigned char ADC12MCTL13_L;
extern volatile unsigned char ADC12MCTL13_H;
extern volatile unsigned int ADC12MCTL14;
extern volatile unsigned char ADC12MCTL14_L;
extern volatile unsigned char ADC12MCTL14_H;
extern volatile unsigned int ADC12MCTL15;
extern volatile unsigned char ADC12MCTL15_L;
extern volatile unsigned char ADC12MCTL15_H;
extern volatile unsigned int ADC12MCTL16;
extern volatile unsigned char ADC12MCTL16_L;
extern volatile unsigned char ADC12MCTL16_H;
extern volatile unsigned int ADC12MCTL17;
extern volatile unsigned char ADC12MCTL17_L;
extern volatile unsigned char ADC12MCTL17_H;
extern volatile unsigned int ADC12MCTL18;
extern volatile unsigned char ADC12MCTL18_L;
extern volatile unsigned char ADC12MCTL18_H;
extern volatile unsigned int ADC12MCTL19;
extern volatile unsigned char ADC12MCTL19_L;
extern volatile unsigned char ADC12MCTL19_H;
extern volatile unsigned int ADC12MCTL20;
extern volatile unsigned char ADC12MCTL20_L;
extern volatile unsigned char ADC12MCTL20_H;
extern volatile unsigned int ADC12MCTL21;
extern volatile unsigned char ADC12MCTL21_L;
extern volatile unsigned char ADC12MCTL21_H;
extern volatile unsigned int ADC12MCTL22;
extern volatile unsigned char ADC12MCTL22_L;
extern volatile unsigned char ADC12MCTL22_H;
extern volatile unsigned int ADC12MCTL23;
extern volatile unsigned char ADC12MCTL23_L;
extern volatile unsigned char ADC12MCTL23_H;
extern volatile unsigned int ADC12MCTL24;
extern volatile unsigned char ADC12MCTL24_L;
extern volatile unsigned char ADC12MCTL24_H;
extern volatile unsigned int ADC12MCTL25;
extern volatile unsigned char ADC12MCTL25_L;
extern volatile unsigned char ADC12MCTL25_H;
extern volatile unsigned int ADC12MCTL26;
extern volatile unsigned char ADC12MCTL26_L;
extern volatile unsigned char ADC12MCTL26_H;
extern volatile unsigned int ADC12MCTL27;
extern volatile unsigned char ADC12MCTL27_L;
extern volatile unsigned char ADC12MCTL27_H;
extern volatile unsigned int ADC12MCTL28;
extern volatile unsigned char ADC12MCTL28_L;
extern volatile unsigned char ADC12MCTL28_H;
extern volatile unsigned int ADC12MCTL29;
extern volatile unsigned char ADC12MCTL29_L;
extern volatile unsigned char ADC12MCTL29_H;
extern volatile unsigned int ADC12MCTL30;
extern volatile unsigned char ADC12MCTL30_L;
extern volatile unsigned char ADC12MCTL30_H;
extern volatile unsigned int ADC12MCTL31;
extern volatile unsigned char ADC12MCTL31_L;
extern volatile unsigned char ADC12MCTL31_H;







extern volatile unsigned int ADC12MEM0;
extern volatile unsigned char ADC12MEM0_L;
extern volatile unsigned char ADC12MEM0_H;
extern volatile unsigned int ADC12MEM1;
extern volatile unsigned char ADC12MEM1_L;
extern volatile unsigned char ADC12MEM1_H;
extern volatile unsigned int ADC12MEM2;
extern volatile unsigned char ADC12MEM2_L;
extern volatile unsigned char ADC12MEM2_H;
extern volatile unsigned int ADC12MEM3;
extern volatile unsigned char ADC12MEM3_L;
extern volatile unsigned char ADC12MEM3_H;
extern volatile unsigned int ADC12MEM4;
extern volatile unsigned char ADC12MEM4_L;
extern volatile unsigned char ADC12MEM4_H;
extern volatile unsigned int ADC12MEM5;
extern volatile unsigned char ADC12MEM5_L;
extern volatile unsigned char ADC12MEM5_H;
extern volatile unsigned int ADC12MEM6;
extern volatile unsigned char ADC12MEM6_L;
extern volatile unsigned char ADC12MEM6_H;
extern volatile unsigned int ADC12MEM7;
extern volatile unsigned char ADC12MEM7_L;
extern volatile unsigned char ADC12MEM7_H;
extern volatile unsigned int ADC12MEM8;
extern volatile unsigned char ADC12MEM8_L;
extern volatile unsigned char ADC12MEM8_H;
extern volatile unsigned int ADC12MEM9;
extern volatile unsigned char ADC12MEM9_L;
extern volatile unsigned char ADC12MEM9_H;
extern volatile unsigned int ADC12MEM10;
extern volatile unsigned char ADC12MEM10_L;
extern volatile unsigned char ADC12MEM10_H;
extern volatile unsigned int ADC12MEM11;
extern volatile unsigned char ADC12MEM11_L;
extern volatile unsigned char ADC12MEM11_H;
extern volatile unsigned int ADC12MEM12;
extern volatile unsigned char ADC12MEM12_L;
extern volatile unsigned char ADC12MEM12_H;
extern volatile unsigned int ADC12MEM13;
extern volatile unsigned char ADC12MEM13_L;
extern volatile unsigned char ADC12MEM13_H;
extern volatile unsigned int ADC12MEM14;
extern volatile unsigned char ADC12MEM14_L;
extern volatile unsigned char ADC12MEM14_H;
extern volatile unsigned int ADC12MEM15;
extern volatile unsigned char ADC12MEM15_L;
extern volatile unsigned char ADC12MEM15_H;
extern volatile unsigned int ADC12MEM16;
extern volatile unsigned char ADC12MEM16_L;
extern volatile unsigned char ADC12MEM16_H;
extern volatile unsigned int ADC12MEM17;
extern volatile unsigned char ADC12MEM17_L;
extern volatile unsigned char ADC12MEM17_H;
extern volatile unsigned int ADC12MEM18;
extern volatile unsigned char ADC12MEM18_L;
extern volatile unsigned char ADC12MEM18_H;
extern volatile unsigned int ADC12MEM19;
extern volatile unsigned char ADC12MEM19_L;
extern volatile unsigned char ADC12MEM19_H;
extern volatile unsigned int ADC12MEM20;
extern volatile unsigned char ADC12MEM20_L;
extern volatile unsigned char ADC12MEM20_H;
extern volatile unsigned int ADC12MEM21;
extern volatile unsigned char ADC12MEM21_L;
extern volatile unsigned char ADC12MEM21_H;
extern volatile unsigned int ADC12MEM22;
extern volatile unsigned char ADC12MEM22_L;
extern volatile unsigned char ADC12MEM22_H;
extern volatile unsigned int ADC12MEM23;
extern volatile unsigned char ADC12MEM23_L;
extern volatile unsigned char ADC12MEM23_H;
extern volatile unsigned int ADC12MEM24;
extern volatile unsigned char ADC12MEM24_L;
extern volatile unsigned char ADC12MEM24_H;
extern volatile unsigned int ADC12MEM25;
extern volatile unsigned char ADC12MEM25_L;
extern volatile unsigned char ADC12MEM25_H;
extern volatile unsigned int ADC12MEM26;
extern volatile unsigned char ADC12MEM26_L;
extern volatile unsigned char ADC12MEM26_H;
extern volatile unsigned int ADC12MEM27;
extern volatile unsigned char ADC12MEM27_L;
extern volatile unsigned char ADC12MEM27_H;
extern volatile unsigned int ADC12MEM28;
extern volatile unsigned char ADC12MEM28_L;
extern volatile unsigned char ADC12MEM28_H;
extern volatile unsigned int ADC12MEM29;
extern volatile unsigned char ADC12MEM29_L;
extern volatile unsigned char ADC12MEM29_H;
extern volatile unsigned int ADC12MEM30;
extern volatile unsigned char ADC12MEM30_L;
extern volatile unsigned char ADC12MEM30_H;
extern volatile unsigned int ADC12MEM31;
extern volatile unsigned char ADC12MEM31_L;
extern volatile unsigned char ADC12MEM31_H;
# 930 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int AESACTL0;
extern volatile unsigned char AESACTL0_L;
extern volatile unsigned char AESACTL0_H;
extern volatile unsigned int AESACTL1;
extern volatile unsigned char AESACTL1_L;
extern volatile unsigned char AESACTL1_H;
extern volatile unsigned int AESASTAT;
extern volatile unsigned char AESASTAT_L;
extern volatile unsigned char AESASTAT_H;
extern volatile unsigned int AESAKEY;
extern volatile unsigned char AESAKEY_L;
extern volatile unsigned char AESAKEY_H;
extern volatile unsigned int AESADIN;
extern volatile unsigned char AESADIN_L;
extern volatile unsigned char AESADIN_H;
extern volatile unsigned int AESADOUT;
extern volatile unsigned char AESADOUT_L;
extern volatile unsigned char AESADOUT_H;
extern volatile unsigned int AESAXDIN;
extern volatile unsigned char AESAXDIN_L;
extern volatile unsigned char AESAXDIN_H;
extern volatile unsigned int AESAXIN;
extern volatile unsigned char AESAXIN_L;
extern volatile unsigned char AESAXIN_H;
# 1071 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int CAPTIO0CTL;
extern volatile unsigned char CAPTIO0CTL_L;
extern volatile unsigned char CAPTIO0CTL_H;
# 1084 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int CAPTIO1CTL;
extern volatile unsigned char CAPTIO1CTL_L;
extern volatile unsigned char CAPTIO1CTL_H;
# 1132 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int CECTL0;
extern volatile unsigned char CECTL0_L;
extern volatile unsigned char CECTL0_H;
extern volatile unsigned int CECTL1;
extern volatile unsigned char CECTL1_L;
extern volatile unsigned char CECTL1_H;
extern volatile unsigned int CECTL2;
extern volatile unsigned char CECTL2_L;
extern volatile unsigned char CECTL2_H;
extern volatile unsigned int CECTL3;
extern volatile unsigned char CECTL3_L;
extern volatile unsigned char CECTL3_H;
extern volatile unsigned int CEINT;
extern volatile unsigned char CEINT_L;
extern volatile unsigned char CEINT_H;
extern volatile unsigned int CEIV;
extern volatile unsigned char CEIV_L;
extern volatile unsigned char CEIV_H;
# 1490 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int CRCDI;
extern volatile unsigned char CRCDI_L;
extern volatile unsigned char CRCDI_H;
extern volatile unsigned int CRCDIRB;
extern volatile unsigned char CRCDIRB_L;
extern volatile unsigned char CRCDIRB_H;
extern volatile unsigned int CRCINIRES;
extern volatile unsigned char CRCINIRES_L;
extern volatile unsigned char CRCINIRES_H;
extern volatile unsigned int CRCRESR;
extern volatile unsigned char CRCRESR_L;
extern volatile unsigned char CRCRESR_H;
# 1512 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int CRC32DIW0;
extern volatile unsigned char CRC32DIW0_L;
extern volatile unsigned char CRC32DIW0_H;
extern volatile unsigned int CRC32DIW1;
extern volatile unsigned char CRC32DIW1_L;
extern volatile unsigned char CRC32DIW1_H;



extern volatile unsigned int CRC32DIRBW1;
extern volatile unsigned char CRC32DIRBW1_L;
extern volatile unsigned char CRC32DIRBW1_H;
extern volatile unsigned int CRC32DIRBW0;
extern volatile unsigned char CRC32DIRBW0_L;
extern volatile unsigned char CRC32DIRBW0_H;



extern volatile unsigned int CRC32INIRESW0;
extern volatile unsigned char CRC32INIRESW0_L;
extern volatile unsigned char CRC32INIRESW0_H;
extern volatile unsigned int CRC32INIRESW1;
extern volatile unsigned char CRC32INIRESW1_L;
extern volatile unsigned char CRC32INIRESW1_H;






extern volatile unsigned int CRC32RESRW1;
extern volatile unsigned char CRC32RESRW1_L;
extern volatile unsigned char CRC32RESRW1_H;
extern volatile unsigned int CRC32RESRW0;
extern volatile unsigned char CRC32RESRW0_L;
extern volatile unsigned char CRC32RESRW0_H;






extern volatile unsigned int CRC16DIW0;
extern volatile unsigned char CRC16DIW0_L;
extern volatile unsigned char CRC16DIW0_H;
extern volatile unsigned int CRC16DIW1;
extern volatile unsigned char CRC16DIW1_L;
extern volatile unsigned char CRC16DIW1_H;


extern volatile unsigned int CRC16DIRBW1;
extern volatile unsigned char CRC16DIRBW1_L;
extern volatile unsigned char CRC16DIRBW1_H;
extern volatile unsigned int CRC16DIRBW0;
extern volatile unsigned char CRC16DIRBW0_L;
extern volatile unsigned char CRC16DIRBW0_H;



extern volatile unsigned int CRC16INIRESW0;
extern volatile unsigned char CRC16INIRESW0_L;
extern volatile unsigned char CRC16INIRESW0_H;




extern volatile unsigned int CRC16RESRW0;
extern volatile unsigned char CRC16RESRW0_L;
extern volatile unsigned char CRC16RESRW0_H;
extern volatile unsigned int CRC16RESRW1;
extern volatile unsigned char CRC16RESRW1_L;
extern volatile unsigned char CRC16RESRW1_H;
# 1594 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int CSCTL0;
extern volatile unsigned char CSCTL0_L;
extern volatile unsigned char CSCTL0_H;
extern volatile unsigned int CSCTL1;
extern volatile unsigned char CSCTL1_L;
extern volatile unsigned char CSCTL1_H;
extern volatile unsigned int CSCTL2;
extern volatile unsigned char CSCTL2_L;
extern volatile unsigned char CSCTL2_H;
extern volatile unsigned int CSCTL3;
extern volatile unsigned char CSCTL3_L;
extern volatile unsigned char CSCTL3_H;
extern volatile unsigned int CSCTL4;
extern volatile unsigned char CSCTL4_L;
extern volatile unsigned char CSCTL4_H;
extern volatile unsigned int CSCTL5;
extern volatile unsigned char CSCTL5_L;
extern volatile unsigned char CSCTL5_H;
extern volatile unsigned int CSCTL6;
extern volatile unsigned char CSCTL6_L;
extern volatile unsigned char CSCTL6_H;
# 1912 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int DMACTL0;
extern volatile unsigned int DMACTL1;
extern volatile unsigned int DMACTL2;
extern volatile unsigned int DMACTL3;
extern volatile unsigned int DMACTL4;
extern volatile unsigned int DMAIV;

extern volatile unsigned int DMA0CTL;
extern volatile unsigned long int DMA0SA;
extern volatile unsigned int DMA0SAL;
extern volatile unsigned int DMA0SAH;
extern volatile unsigned long int DMA0DA;
extern volatile unsigned int DMA0DAL;
extern volatile unsigned int DMA0DAH;
extern volatile unsigned int DMA0SZ;

extern volatile unsigned int DMA1CTL;
extern volatile unsigned long int DMA1SA;
extern volatile unsigned int DMA1SAL;
extern volatile unsigned int DMA1SAH;
extern volatile unsigned long int DMA1DA;
extern volatile unsigned int DMA1DAL;
extern volatile unsigned int DMA1DAH;
extern volatile unsigned int DMA1SZ;

extern volatile unsigned int DMA2CTL;
extern volatile unsigned long int DMA2SA;
extern volatile unsigned int DMA2SAL;
extern volatile unsigned int DMA2SAH;
extern volatile unsigned long int DMA2DA;
extern volatile unsigned int DMA2DAL;
extern volatile unsigned int DMA2DAH;
extern volatile unsigned int DMA2SZ;
# 2223 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int ESIDEBUG1;
extern volatile unsigned char ESIDEBUG1_L;
extern volatile unsigned char ESIDEBUG1_H;
extern volatile unsigned int ESIDEBUG2;
extern volatile unsigned char ESIDEBUG2_L;
extern volatile unsigned char ESIDEBUG2_H;
extern volatile unsigned int ESIDEBUG3;
extern volatile unsigned char ESIDEBUG3_L;
extern volatile unsigned char ESIDEBUG3_H;
extern volatile unsigned int ESIDEBUG4;
extern volatile unsigned char ESIDEBUG4_L;
extern volatile unsigned char ESIDEBUG4_H;
extern volatile unsigned int ESIDEBUG5;
extern volatile unsigned char ESIDEBUG5_L;
extern volatile unsigned char ESIDEBUG5_H;
extern volatile unsigned int ESICNT0;
extern volatile unsigned char ESICNT0_L;
extern volatile unsigned char ESICNT0_H;
extern volatile unsigned int ESICNT1;
extern volatile unsigned char ESICNT1_L;
extern volatile unsigned char ESICNT1_H;
extern volatile unsigned int ESICNT2;
extern volatile unsigned char ESICNT2_L;
extern volatile unsigned char ESICNT2_H;
extern volatile unsigned int ESICNT3;
extern volatile unsigned char ESICNT3_L;
extern volatile unsigned char ESICNT3_H;
extern volatile unsigned int ESIIV;
extern volatile unsigned char ESIIV_L;
extern volatile unsigned char ESIIV_H;
extern volatile unsigned int ESIINT1;
extern volatile unsigned char ESIINT1_L;
extern volatile unsigned char ESIINT1_H;
extern volatile unsigned int ESIINT2;
extern volatile unsigned char ESIINT2_L;
extern volatile unsigned char ESIINT2_H;
extern volatile unsigned int ESIAFE;
extern volatile unsigned char ESIAFE_L;
extern volatile unsigned char ESIAFE_H;
extern volatile unsigned int ESIPPU;
extern volatile unsigned char ESIPPU_L;
extern volatile unsigned char ESIPPU_H;
extern volatile unsigned int ESITSM;
extern volatile unsigned char ESITSM_L;
extern volatile unsigned char ESITSM_H;
extern volatile unsigned int ESIPSM;
extern volatile unsigned char ESIPSM_L;
extern volatile unsigned char ESIPSM_H;
extern volatile unsigned int ESIOSC;
extern volatile unsigned char ESIOSC_L;
extern volatile unsigned char ESIOSC_H;
extern volatile unsigned int ESICTL;
extern volatile unsigned char ESICTL_L;
extern volatile unsigned char ESICTL_H;
extern volatile unsigned int ESITHR1;
extern volatile unsigned char ESITHR1_L;
extern volatile unsigned char ESITHR1_H;
extern volatile unsigned int ESITHR2;
extern volatile unsigned char ESITHR2_L;
extern volatile unsigned char ESITHR2_H;
extern volatile unsigned int ESIDAC1R0;
extern volatile unsigned char ESIDAC1R0_L;
extern volatile unsigned char ESIDAC1R0_H;
extern volatile unsigned int ESIDAC1R1;
extern volatile unsigned char ESIDAC1R1_L;
extern volatile unsigned char ESIDAC1R1_H;
extern volatile unsigned int ESIDAC1R2;
extern volatile unsigned char ESIDAC1R2_L;
extern volatile unsigned char ESIDAC1R2_H;
extern volatile unsigned int ESIDAC1R3;
extern volatile unsigned char ESIDAC1R3_L;
extern volatile unsigned char ESIDAC1R3_H;
extern volatile unsigned int ESIDAC1R4;
extern volatile unsigned char ESIDAC1R4_L;
extern volatile unsigned char ESIDAC1R4_H;
extern volatile unsigned int ESIDAC1R5;
extern volatile unsigned char ESIDAC1R5_L;
extern volatile unsigned char ESIDAC1R5_H;
extern volatile unsigned int ESIDAC1R6;
extern volatile unsigned char ESIDAC1R6_L;
extern volatile unsigned char ESIDAC1R6_H;
extern volatile unsigned int ESIDAC1R7;
extern volatile unsigned char ESIDAC1R7_L;
extern volatile unsigned char ESIDAC1R7_H;
extern volatile unsigned int ESIDAC2R0;
extern volatile unsigned char ESIDAC2R0_L;
extern volatile unsigned char ESIDAC2R0_H;
extern volatile unsigned int ESIDAC2R1;
extern volatile unsigned char ESIDAC2R1_L;
extern volatile unsigned char ESIDAC2R1_H;
extern volatile unsigned int ESIDAC2R2;
extern volatile unsigned char ESIDAC2R2_L;
extern volatile unsigned char ESIDAC2R2_H;
extern volatile unsigned int ESIDAC2R3;
extern volatile unsigned char ESIDAC2R3_L;
extern volatile unsigned char ESIDAC2R3_H;
extern volatile unsigned int ESIDAC2R4;
extern volatile unsigned char ESIDAC2R4_L;
extern volatile unsigned char ESIDAC2R4_H;
extern volatile unsigned int ESIDAC2R5;
extern volatile unsigned char ESIDAC2R5_L;
extern volatile unsigned char ESIDAC2R5_H;
extern volatile unsigned int ESIDAC2R6;
extern volatile unsigned char ESIDAC2R6_L;
extern volatile unsigned char ESIDAC2R6_H;
extern volatile unsigned int ESIDAC2R7;
extern volatile unsigned char ESIDAC2R7_L;
extern volatile unsigned char ESIDAC2R7_H;
extern volatile unsigned int ESITSM0;
extern volatile unsigned char ESITSM0_L;
extern volatile unsigned char ESITSM0_H;
extern volatile unsigned int ESITSM1;
extern volatile unsigned char ESITSM1_L;
extern volatile unsigned char ESITSM1_H;
extern volatile unsigned int ESITSM2;
extern volatile unsigned char ESITSM2_L;
extern volatile unsigned char ESITSM2_H;
extern volatile unsigned int ESITSM3;
extern volatile unsigned char ESITSM3_L;
extern volatile unsigned char ESITSM3_H;
extern volatile unsigned int ESITSM4;
extern volatile unsigned char ESITSM4_L;
extern volatile unsigned char ESITSM4_H;
extern volatile unsigned int ESITSM5;
extern volatile unsigned char ESITSM5_L;
extern volatile unsigned char ESITSM5_H;
extern volatile unsigned int ESITSM6;
extern volatile unsigned char ESITSM6_L;
extern volatile unsigned char ESITSM6_H;
extern volatile unsigned int ESITSM7;
extern volatile unsigned char ESITSM7_L;
extern volatile unsigned char ESITSM7_H;
extern volatile unsigned int ESITSM8;
extern volatile unsigned char ESITSM8_L;
extern volatile unsigned char ESITSM8_H;
extern volatile unsigned int ESITSM9;
extern volatile unsigned char ESITSM9_L;
extern volatile unsigned char ESITSM9_H;
extern volatile unsigned int ESITSM10;
extern volatile unsigned char ESITSM10_L;
extern volatile unsigned char ESITSM10_H;
extern volatile unsigned int ESITSM11;
extern volatile unsigned char ESITSM11_L;
extern volatile unsigned char ESITSM11_H;
extern volatile unsigned int ESITSM12;
extern volatile unsigned char ESITSM12_L;
extern volatile unsigned char ESITSM12_H;
extern volatile unsigned int ESITSM13;
extern volatile unsigned char ESITSM13_L;
extern volatile unsigned char ESITSM13_H;
extern volatile unsigned int ESITSM14;
extern volatile unsigned char ESITSM14_L;
extern volatile unsigned char ESITSM14_H;
extern volatile unsigned int ESITSM15;
extern volatile unsigned char ESITSM15_L;
extern volatile unsigned char ESITSM15_H;
extern volatile unsigned int ESITSM16;
extern volatile unsigned char ESITSM16_L;
extern volatile unsigned char ESITSM16_H;
extern volatile unsigned int ESITSM17;
extern volatile unsigned char ESITSM17_L;
extern volatile unsigned char ESITSM17_H;
extern volatile unsigned int ESITSM18;
extern volatile unsigned char ESITSM18_L;
extern volatile unsigned char ESITSM18_H;
extern volatile unsigned int ESITSM19;
extern volatile unsigned char ESITSM19_L;
extern volatile unsigned char ESITSM19_H;
extern volatile unsigned int ESITSM20;
extern volatile unsigned char ESITSM20_L;
extern volatile unsigned char ESITSM20_H;
extern volatile unsigned int ESITSM21;
extern volatile unsigned char ESITSM21_L;
extern volatile unsigned char ESITSM21_H;
extern volatile unsigned int ESITSM22;
extern volatile unsigned char ESITSM22_L;
extern volatile unsigned char ESITSM22_H;
extern volatile unsigned int ESITSM23;
extern volatile unsigned char ESITSM23_L;
extern volatile unsigned char ESITSM23_H;
extern volatile unsigned int ESITSM24;
extern volatile unsigned char ESITSM24_L;
extern volatile unsigned char ESITSM24_H;
extern volatile unsigned int ESITSM25;
extern volatile unsigned char ESITSM25_L;
extern volatile unsigned char ESITSM25_H;
extern volatile unsigned int ESITSM26;
extern volatile unsigned char ESITSM26_L;
extern volatile unsigned char ESITSM26_H;
extern volatile unsigned int ESITSM27;
extern volatile unsigned char ESITSM27_L;
extern volatile unsigned char ESITSM27_H;
extern volatile unsigned int ESITSM28;
extern volatile unsigned char ESITSM28_L;
extern volatile unsigned char ESITSM28_H;
extern volatile unsigned int ESITSM29;
extern volatile unsigned char ESITSM29_L;
extern volatile unsigned char ESITSM29_H;
extern volatile unsigned int ESITSM30;
extern volatile unsigned char ESITSM30_L;
extern volatile unsigned char ESITSM30_H;
extern volatile unsigned int ESITSM31;
extern volatile unsigned char ESITSM31_L;
extern volatile unsigned char ESITSM31_H;
# 2876 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned char ESIRAM0;
extern volatile unsigned char ESIRAM1;
extern volatile unsigned char ESIRAM2;
extern volatile unsigned char ESIRAM3;
extern volatile unsigned char ESIRAM4;
extern volatile unsigned char ESIRAM5;
extern volatile unsigned char ESIRAM6;
extern volatile unsigned char ESIRAM7;
extern volatile unsigned char ESIRAM8;
extern volatile unsigned char ESIRAM9;
extern volatile unsigned char ESIRAM10;
extern volatile unsigned char ESIRAM11;
extern volatile unsigned char ESIRAM12;
extern volatile unsigned char ESIRAM13;
extern volatile unsigned char ESIRAM14;
extern volatile unsigned char ESIRAM15;
extern volatile unsigned char ESIRAM16;
extern volatile unsigned char ESIRAM17;
extern volatile unsigned char ESIRAM18;
extern volatile unsigned char ESIRAM19;
extern volatile unsigned char ESIRAM20;
extern volatile unsigned char ESIRAM21;
extern volatile unsigned char ESIRAM22;
extern volatile unsigned char ESIRAM23;
extern volatile unsigned char ESIRAM24;
extern volatile unsigned char ESIRAM25;
extern volatile unsigned char ESIRAM26;
extern volatile unsigned char ESIRAM27;
extern volatile unsigned char ESIRAM28;
extern volatile unsigned char ESIRAM29;
extern volatile unsigned char ESIRAM30;
extern volatile unsigned char ESIRAM31;
extern volatile unsigned char ESIRAM32;
extern volatile unsigned char ESIRAM33;
extern volatile unsigned char ESIRAM34;
extern volatile unsigned char ESIRAM35;
extern volatile unsigned char ESIRAM36;
extern volatile unsigned char ESIRAM37;
extern volatile unsigned char ESIRAM38;
extern volatile unsigned char ESIRAM39;
extern volatile unsigned char ESIRAM40;
extern volatile unsigned char ESIRAM41;
extern volatile unsigned char ESIRAM42;
extern volatile unsigned char ESIRAM43;
extern volatile unsigned char ESIRAM44;
extern volatile unsigned char ESIRAM45;
extern volatile unsigned char ESIRAM46;
extern volatile unsigned char ESIRAM47;
extern volatile unsigned char ESIRAM48;
extern volatile unsigned char ESIRAM49;
extern volatile unsigned char ESIRAM50;
extern volatile unsigned char ESIRAM51;
extern volatile unsigned char ESIRAM52;
extern volatile unsigned char ESIRAM53;
extern volatile unsigned char ESIRAM54;
extern volatile unsigned char ESIRAM55;
extern volatile unsigned char ESIRAM56;
extern volatile unsigned char ESIRAM57;
extern volatile unsigned char ESIRAM58;
extern volatile unsigned char ESIRAM59;
extern volatile unsigned char ESIRAM60;
extern volatile unsigned char ESIRAM61;
extern volatile unsigned char ESIRAM62;
extern volatile unsigned char ESIRAM63;
extern volatile unsigned char ESIRAM64;
extern volatile unsigned char ESIRAM65;
extern volatile unsigned char ESIRAM66;
extern volatile unsigned char ESIRAM67;
extern volatile unsigned char ESIRAM68;
extern volatile unsigned char ESIRAM69;
extern volatile unsigned char ESIRAM70;
extern volatile unsigned char ESIRAM71;
extern volatile unsigned char ESIRAM72;
extern volatile unsigned char ESIRAM73;
extern volatile unsigned char ESIRAM74;
extern volatile unsigned char ESIRAM75;
extern volatile unsigned char ESIRAM76;
extern volatile unsigned char ESIRAM77;
extern volatile unsigned char ESIRAM78;
extern volatile unsigned char ESIRAM79;
extern volatile unsigned char ESIRAM80;
extern volatile unsigned char ESIRAM81;
extern volatile unsigned char ESIRAM82;
extern volatile unsigned char ESIRAM83;
extern volatile unsigned char ESIRAM84;
extern volatile unsigned char ESIRAM85;
extern volatile unsigned char ESIRAM86;
extern volatile unsigned char ESIRAM87;
extern volatile unsigned char ESIRAM88;
extern volatile unsigned char ESIRAM89;
extern volatile unsigned char ESIRAM90;
extern volatile unsigned char ESIRAM91;
extern volatile unsigned char ESIRAM92;
extern volatile unsigned char ESIRAM93;
extern volatile unsigned char ESIRAM94;
extern volatile unsigned char ESIRAM95;
extern volatile unsigned char ESIRAM96;
extern volatile unsigned char ESIRAM97;
extern volatile unsigned char ESIRAM98;
extern volatile unsigned char ESIRAM99;
extern volatile unsigned char ESIRAM100;
extern volatile unsigned char ESIRAM101;
extern volatile unsigned char ESIRAM102;
extern volatile unsigned char ESIRAM103;
extern volatile unsigned char ESIRAM104;
extern volatile unsigned char ESIRAM105;
extern volatile unsigned char ESIRAM106;
extern volatile unsigned char ESIRAM107;
extern volatile unsigned char ESIRAM108;
extern volatile unsigned char ESIRAM109;
extern volatile unsigned char ESIRAM110;
extern volatile unsigned char ESIRAM111;
extern volatile unsigned char ESIRAM112;
extern volatile unsigned char ESIRAM113;
extern volatile unsigned char ESIRAM114;
extern volatile unsigned char ESIRAM115;
extern volatile unsigned char ESIRAM116;
extern volatile unsigned char ESIRAM117;
extern volatile unsigned char ESIRAM118;
extern volatile unsigned char ESIRAM119;
extern volatile unsigned char ESIRAM120;
extern volatile unsigned char ESIRAM121;
extern volatile unsigned char ESIRAM122;
extern volatile unsigned char ESIRAM123;
extern volatile unsigned char ESIRAM124;
extern volatile unsigned char ESIRAM125;
extern volatile unsigned char ESIRAM126;
extern volatile unsigned char ESIRAM127;
# 3012 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int FRCTL0;
extern volatile unsigned char FRCTL0_L;
extern volatile unsigned char FRCTL0_H;
extern volatile unsigned int GCCTL0;
extern volatile unsigned char GCCTL0_L;
extern volatile unsigned char GCCTL0_H;
extern volatile unsigned int GCCTL1;
extern volatile unsigned char GCCTL1_L;
extern volatile unsigned char GCCTL1_H;
# 3093 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int LCDCCTL0;
extern volatile unsigned char LCDCCTL0_L;
extern volatile unsigned char LCDCCTL0_H;
extern volatile unsigned int LCDCCTL1;
extern volatile unsigned char LCDCCTL1_L;
extern volatile unsigned char LCDCCTL1_H;
extern volatile unsigned int LCDCBLKCTL;
extern volatile unsigned char LCDCBLKCTL_L;
extern volatile unsigned char LCDCBLKCTL_H;
extern volatile unsigned int LCDCMEMCTL;
extern volatile unsigned char LCDCMEMCTL_L;
extern volatile unsigned char LCDCMEMCTL_H;
extern volatile unsigned int LCDCVCTL;
extern volatile unsigned char LCDCVCTL_L;
extern volatile unsigned char LCDCVCTL_H;
extern volatile unsigned int LCDCPCTL0;
extern volatile unsigned char LCDCPCTL0_L;
extern volatile unsigned char LCDCPCTL0_H;
extern volatile unsigned int LCDCPCTL1;
extern volatile unsigned char LCDCPCTL1_L;
extern volatile unsigned char LCDCPCTL1_H;
extern volatile unsigned int LCDCPCTL2;
extern volatile unsigned char LCDCPCTL2_L;
extern volatile unsigned char LCDCPCTL2_H;
extern volatile unsigned int LCDCCPCTL;
extern volatile unsigned char LCDCCPCTL_L;
extern volatile unsigned char LCDCCPCTL_H;
extern volatile unsigned int LCDCIV;
# 3555 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned char LCDM1;






extern volatile unsigned char LCDM2;
extern volatile unsigned char LCDM3;
extern volatile unsigned char LCDM4;
extern volatile unsigned char LCDM5;
extern volatile unsigned char LCDM6;
extern volatile unsigned char LCDM7;
extern volatile unsigned char LCDM8;
extern volatile unsigned char LCDM9;
extern volatile unsigned char LCDM10;
extern volatile unsigned char LCDM11;
extern volatile unsigned char LCDM12;
extern volatile unsigned char LCDM13;
extern volatile unsigned char LCDM14;
extern volatile unsigned char LCDM15;
extern volatile unsigned char LCDM16;
extern volatile unsigned char LCDM17;
extern volatile unsigned char LCDM18;
extern volatile unsigned char LCDM19;
extern volatile unsigned char LCDM20;
extern volatile unsigned char LCDM21;
extern volatile unsigned char LCDM22;
extern volatile unsigned char LCDM23;
extern volatile unsigned char LCDM24;
extern volatile unsigned char LCDM25;
extern volatile unsigned char LCDM26;
extern volatile unsigned char LCDM27;
extern volatile unsigned char LCDM28;
extern volatile unsigned char LCDM29;
extern volatile unsigned char LCDM30;
extern volatile unsigned char LCDM31;
extern volatile unsigned char LCDM32;
extern volatile unsigned char LCDM33;
extern volatile unsigned char LCDM34;
extern volatile unsigned char LCDM35;
extern volatile unsigned char LCDM36;
extern volatile unsigned char LCDM37;
extern volatile unsigned char LCDM38;
extern volatile unsigned char LCDM39;
extern volatile unsigned char LCDM40;
extern volatile unsigned char LCDM41;
extern volatile unsigned char LCDM42;
extern volatile unsigned char LCDM43;

extern volatile unsigned char LCDBM1;






extern volatile unsigned char LCDBM2;
extern volatile unsigned char LCDBM3;
extern volatile unsigned char LCDBM4;
extern volatile unsigned char LCDBM5;
extern volatile unsigned char LCDBM6;
extern volatile unsigned char LCDBM7;
extern volatile unsigned char LCDBM8;
extern volatile unsigned char LCDBM9;
extern volatile unsigned char LCDBM10;
extern volatile unsigned char LCDBM11;
extern volatile unsigned char LCDBM12;
extern volatile unsigned char LCDBM13;
extern volatile unsigned char LCDBM14;
extern volatile unsigned char LCDBM15;
extern volatile unsigned char LCDBM16;
extern volatile unsigned char LCDBM17;
extern volatile unsigned char LCDBM18;
extern volatile unsigned char LCDBM19;
extern volatile unsigned char LCDBM20;
extern volatile unsigned char LCDBM21;
extern volatile unsigned char LCDBM22;
# 3648 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int MPUCTL0;
extern volatile unsigned char MPUCTL0_L;
extern volatile unsigned char MPUCTL0_H;
extern volatile unsigned int MPUCTL1;
extern volatile unsigned char MPUCTL1_L;
extern volatile unsigned char MPUCTL1_H;
extern volatile unsigned int MPUSEGB2;
extern volatile unsigned char MPUSEGB2_L;
extern volatile unsigned char MPUSEGB2_H;
extern volatile unsigned int MPUSEGB1;
extern volatile unsigned char MPUSEGB1_L;
extern volatile unsigned char MPUSEGB1_H;
extern volatile unsigned int MPUSAM;
extern volatile unsigned char MPUSAM_L;
extern volatile unsigned char MPUSAM_H;
extern volatile unsigned int MPUIPC0;
extern volatile unsigned char MPUIPC0_L;
extern volatile unsigned char MPUIPC0_H;
extern volatile unsigned int MPUIPSEGB2;
extern volatile unsigned char MPUIPSEGB2_L;
extern volatile unsigned char MPUIPSEGB2_H;
extern volatile unsigned int MPUIPSEGB1;
extern volatile unsigned char MPUIPSEGB1_L;
extern volatile unsigned char MPUIPSEGB1_H;
# 3779 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int MPY;
extern volatile unsigned char MPY_L;
extern volatile unsigned char MPY_H;
extern volatile unsigned int MPYS;
extern volatile unsigned char MPYS_L;
extern volatile unsigned char MPYS_H;
extern volatile unsigned int MAC;
extern volatile unsigned char MAC_L;
extern volatile unsigned char MAC_H;
extern volatile unsigned int MACS;
extern volatile unsigned char MACS_L;
extern volatile unsigned char MACS_H;
extern volatile unsigned int OP2;
extern volatile unsigned char OP2_L;
extern volatile unsigned char OP2_H;
extern volatile unsigned int RESLO;
extern volatile unsigned char RESLO_L;
extern volatile unsigned char RESLO_H;
extern volatile unsigned int RESHI;
extern volatile unsigned char RESHI_L;
extern volatile unsigned char RESHI_H;
extern volatile unsigned int SUMEXT;
extern volatile unsigned char SUMEXT_L;
extern volatile unsigned char SUMEXT_H;

extern volatile unsigned int MPY32L;
extern volatile unsigned char MPY32L_L;
extern volatile unsigned char MPY32L_H;
extern volatile unsigned int MPY32H;
extern volatile unsigned char MPY32H_L;
extern volatile unsigned char MPY32H_H;
extern volatile unsigned int MPYS32L;
extern volatile unsigned char MPYS32L_L;
extern volatile unsigned char MPYS32L_H;
extern volatile unsigned int MPYS32H;
extern volatile unsigned char MPYS32H_L;
extern volatile unsigned char MPYS32H_H;
extern volatile unsigned int MAC32L;
extern volatile unsigned char MAC32L_L;
extern volatile unsigned char MAC32L_H;
extern volatile unsigned int MAC32H;
extern volatile unsigned char MAC32H_L;
extern volatile unsigned char MAC32H_H;
extern volatile unsigned int MACS32L;
extern volatile unsigned char MACS32L_L;
extern volatile unsigned char MACS32L_H;
extern volatile unsigned int MACS32H;
extern volatile unsigned char MACS32H_L;
extern volatile unsigned char MACS32H_H;
extern volatile unsigned int OP2L;
extern volatile unsigned char OP2L_L;
extern volatile unsigned char OP2L_H;
extern volatile unsigned int OP2H;
extern volatile unsigned char OP2H_L;
extern volatile unsigned char OP2H_H;
extern volatile unsigned int RES0;
extern volatile unsigned char RES0_L;
extern volatile unsigned char RES0_H;
extern volatile unsigned int RES1;
extern volatile unsigned char RES1_L;
extern volatile unsigned char RES1_H;
extern volatile unsigned int RES2;
extern volatile unsigned char RES2_L;
extern volatile unsigned char RES2_H;
extern volatile unsigned int RES3;
extern volatile unsigned char RES3_L;
extern volatile unsigned char RES3_H;
extern volatile unsigned int MPY32CTL0;
extern volatile unsigned char MPY32CTL0_L;
extern volatile unsigned char MPY32CTL0_H;
# 3909 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PMMCTL0;
extern volatile unsigned char PMMCTL0_L;
extern volatile unsigned char PMMCTL0_H;
extern volatile unsigned int PMMIFG;
extern volatile unsigned char PMMIFG_L;
extern volatile unsigned char PMMIFG_H;
extern volatile unsigned int PM5CTL0;
extern volatile unsigned char PM5CTL0_L;
extern volatile unsigned char PM5CTL0_H;
# 3976 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PAIN;
extern volatile unsigned char PAIN_L;
extern volatile unsigned char PAIN_H;
extern volatile unsigned int PAOUT;
extern volatile unsigned char PAOUT_L;
extern volatile unsigned char PAOUT_H;
extern volatile unsigned int PADIR;
extern volatile unsigned char PADIR_L;
extern volatile unsigned char PADIR_H;
extern volatile unsigned int PAREN;
extern volatile unsigned char PAREN_L;
extern volatile unsigned char PAREN_H;
extern volatile unsigned int PASEL0;
extern volatile unsigned char PASEL0_L;
extern volatile unsigned char PASEL0_H;
extern volatile unsigned int PASEL1;
extern volatile unsigned char PASEL1_L;
extern volatile unsigned char PASEL1_H;
extern volatile unsigned int PASELC;
extern volatile unsigned char PASELC_L;
extern volatile unsigned char PASELC_H;
extern volatile unsigned int PAIES;
extern volatile unsigned char PAIES_L;
extern volatile unsigned char PAIES_H;
extern volatile unsigned int PAIE;
extern volatile unsigned char PAIE_L;
extern volatile unsigned char PAIE_H;
extern volatile unsigned int PAIFG;
extern volatile unsigned char PAIFG_L;
extern volatile unsigned char PAIFG_H;


extern volatile unsigned int P1IV;
extern volatile unsigned int P2IV;
# 4074 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PBIN;
extern volatile unsigned char PBIN_L;
extern volatile unsigned char PBIN_H;
extern volatile unsigned int PBOUT;
extern volatile unsigned char PBOUT_L;
extern volatile unsigned char PBOUT_H;
extern volatile unsigned int PBDIR;
extern volatile unsigned char PBDIR_L;
extern volatile unsigned char PBDIR_H;
extern volatile unsigned int PBREN;
extern volatile unsigned char PBREN_L;
extern volatile unsigned char PBREN_H;
extern volatile unsigned int PBSEL0;
extern volatile unsigned char PBSEL0_L;
extern volatile unsigned char PBSEL0_H;
extern volatile unsigned int PBSEL1;
extern volatile unsigned char PBSEL1_L;
extern volatile unsigned char PBSEL1_H;
extern volatile unsigned int PBSELC;
extern volatile unsigned char PBSELC_L;
extern volatile unsigned char PBSELC_H;
extern volatile unsigned int PBIES;
extern volatile unsigned char PBIES_L;
extern volatile unsigned char PBIES_H;
extern volatile unsigned int PBIE;
extern volatile unsigned char PBIE_L;
extern volatile unsigned char PBIE_H;
extern volatile unsigned int PBIFG;
extern volatile unsigned char PBIFG_L;
extern volatile unsigned char PBIFG_H;


extern volatile unsigned int P3IV;
extern volatile unsigned int P4IV;
# 4172 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PCIN;
extern volatile unsigned char PCIN_L;
extern volatile unsigned char PCIN_H;
extern volatile unsigned int PCOUT;
extern volatile unsigned char PCOUT_L;
extern volatile unsigned char PCOUT_H;
extern volatile unsigned int PCDIR;
extern volatile unsigned char PCDIR_L;
extern volatile unsigned char PCDIR_H;
extern volatile unsigned int PCREN;
extern volatile unsigned char PCREN_L;
extern volatile unsigned char PCREN_H;
extern volatile unsigned int PCSEL0;
extern volatile unsigned char PCSEL0_L;
extern volatile unsigned char PCSEL0_H;
extern volatile unsigned int PCSEL1;
extern volatile unsigned char PCSEL1_L;
extern volatile unsigned char PCSEL1_H;
extern volatile unsigned int PCSELC;
extern volatile unsigned char PCSELC_L;
extern volatile unsigned char PCSELC_H;
# 4231 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PDIN;
extern volatile unsigned char PDIN_L;
extern volatile unsigned char PDIN_H;
extern volatile unsigned int PDOUT;
extern volatile unsigned char PDOUT_L;
extern volatile unsigned char PDOUT_H;
extern volatile unsigned int PDDIR;
extern volatile unsigned char PDDIR_L;
extern volatile unsigned char PDDIR_H;
extern volatile unsigned int PDREN;
extern volatile unsigned char PDREN_L;
extern volatile unsigned char PDREN_H;
extern volatile unsigned int PDSEL0;
extern volatile unsigned char PDSEL0_L;
extern volatile unsigned char PDSEL0_H;
extern volatile unsigned int PDSEL1;
extern volatile unsigned char PDSEL1_L;
extern volatile unsigned char PDSEL1_H;
extern volatile unsigned int PDSELC;
extern volatile unsigned char PDSELC_L;
extern volatile unsigned char PDSELC_H;
# 4290 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PEIN;
extern volatile unsigned char PEIN_L;
extern volatile unsigned char PEIN_H;
extern volatile unsigned int PEOUT;
extern volatile unsigned char PEOUT_L;
extern volatile unsigned char PEOUT_H;
extern volatile unsigned int PEDIR;
extern volatile unsigned char PEDIR_L;
extern volatile unsigned char PEDIR_H;
extern volatile unsigned int PEREN;
extern volatile unsigned char PEREN_L;
extern volatile unsigned char PEREN_H;
extern volatile unsigned int PESEL0;
extern volatile unsigned char PESEL0_L;
extern volatile unsigned char PESEL0_H;
extern volatile unsigned int PESEL1;
extern volatile unsigned char PESEL1_L;
extern volatile unsigned char PESEL1_H;
extern volatile unsigned int PESELC;
extern volatile unsigned char PESELC_L;
extern volatile unsigned char PESELC_H;
# 4339 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int PJIN;
extern volatile unsigned char PJIN_L;
extern volatile unsigned char PJIN_H;
extern volatile unsigned int PJOUT;
extern volatile unsigned char PJOUT_L;
extern volatile unsigned char PJOUT_H;
extern volatile unsigned int PJDIR;
extern volatile unsigned char PJDIR_L;
extern volatile unsigned char PJDIR_H;
extern volatile unsigned int PJREN;
extern volatile unsigned char PJREN_L;
extern volatile unsigned char PJREN_H;
extern volatile unsigned int PJSEL0;
extern volatile unsigned char PJSEL0_L;
extern volatile unsigned char PJSEL0_H;
extern volatile unsigned int PJSEL1;
extern volatile unsigned char PJSEL1_L;
extern volatile unsigned char PJSEL1_H;
extern volatile unsigned int PJSELC;
extern volatile unsigned char PJSELC_L;
extern volatile unsigned char PJSELC_H;
# 4368 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int RCCTL0;
extern volatile unsigned char RCCTL0_L;
extern volatile unsigned char RCCTL0_H;
# 4418 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int REFCTL0;
extern volatile unsigned char REFCTL0_L;
extern volatile unsigned char REFCTL0_H;
# 4475 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int RTCCTL0;
extern volatile unsigned char RTCCTL0_L;
extern volatile unsigned char RTCCTL0_H;

extern volatile unsigned int RTCCTL13;
extern volatile unsigned char RTCCTL13_L;
extern volatile unsigned char RTCCTL13_H;


extern volatile unsigned int RTCOCAL;
extern volatile unsigned char RTCOCAL_L;
extern volatile unsigned char RTCOCAL_H;
extern volatile unsigned int RTCTCMP;
extern volatile unsigned char RTCTCMP_L;
extern volatile unsigned char RTCTCMP_H;
extern volatile unsigned int RTCPS0CTL;
extern volatile unsigned char RTCPS0CTL_L;
extern volatile unsigned char RTCPS0CTL_H;
extern volatile unsigned int RTCPS1CTL;
extern volatile unsigned char RTCPS1CTL_L;
extern volatile unsigned char RTCPS1CTL_H;
extern volatile unsigned int RTCPS;
extern volatile unsigned char RTCPS_L;
extern volatile unsigned char RTCPS_H;
extern volatile unsigned int RTCIV;
extern volatile unsigned int RTCTIM0;
extern volatile unsigned char RTCTIM0_L;
extern volatile unsigned char RTCTIM0_H;
extern volatile unsigned int RTCTIM1;
extern volatile unsigned char RTCTIM1_L;
extern volatile unsigned char RTCTIM1_H;
extern volatile unsigned int RTCDATE;
extern volatile unsigned char RTCDATE_L;
extern volatile unsigned char RTCDATE_H;
extern volatile unsigned int RTCYEAR;
extern volatile unsigned char RTCYEAR_L;
extern volatile unsigned char RTCYEAR_H;
extern volatile unsigned int RTCAMINHR;
extern volatile unsigned char RTCAMINHR_L;
extern volatile unsigned char RTCAMINHR_H;
extern volatile unsigned int RTCADOWDAY;
extern volatile unsigned char RTCADOWDAY_L;
extern volatile unsigned char RTCADOWDAY_H;
extern volatile unsigned int BIN2BCD;
extern volatile unsigned int BCD2BIN;
# 4815 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int SFRIE1;
extern volatile unsigned char SFRIE1_L;
extern volatile unsigned char SFRIE1_H;
# 4836 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int SFRIFG1;
extern volatile unsigned char SFRIFG1_L;
extern volatile unsigned char SFRIFG1_H;
# 4858 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int SFRRPCR;
extern volatile unsigned char SFRRPCR_L;
extern volatile unsigned char SFRRPCR_H;
# 4879 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int SYSCTL;
extern volatile unsigned char SYSCTL_L;
extern volatile unsigned char SYSCTL_H;
extern volatile unsigned int SYSJMBC;
extern volatile unsigned char SYSJMBC_L;
extern volatile unsigned char SYSJMBC_H;
extern volatile unsigned int SYSJMBI0;
extern volatile unsigned char SYSJMBI0_L;
extern volatile unsigned char SYSJMBI0_H;
extern volatile unsigned int SYSJMBI1;
extern volatile unsigned char SYSJMBI1_L;
extern volatile unsigned char SYSJMBI1_H;
extern volatile unsigned int SYSJMBO0;
extern volatile unsigned char SYSJMBO0_L;
extern volatile unsigned char SYSJMBO0_H;
extern volatile unsigned int SYSJMBO1;
extern volatile unsigned char SYSJMBO1_L;
extern volatile unsigned char SYSJMBO1_H;

extern volatile unsigned int SYSUNIV;
extern volatile unsigned char SYSUNIV_L;
extern volatile unsigned char SYSUNIV_H;
extern volatile unsigned int SYSSNIV;
extern volatile unsigned char SYSSNIV_L;
extern volatile unsigned char SYSSNIV_H;
extern volatile unsigned int SYSRSTIV;
extern volatile unsigned char SYSRSTIV_L;
extern volatile unsigned char SYSRSTIV_H;
# 5035 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int TA0CTL;
extern volatile unsigned int TA0CCTL0;
extern volatile unsigned int TA0CCTL1;
extern volatile unsigned int TA0CCTL2;
extern volatile unsigned int TA0R;
extern volatile unsigned int TA0CCR0;
extern volatile unsigned int TA0CCR1;
extern volatile unsigned int TA0CCR2;
extern volatile unsigned int TA0IV;
extern volatile unsigned int TA0EX0;
# 5153 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int TA1CTL;
extern volatile unsigned int TA1CCTL0;
extern volatile unsigned int TA1CCTL1;
extern volatile unsigned int TA1CCTL2;
extern volatile unsigned int TA1R;
extern volatile unsigned int TA1CCR0;
extern volatile unsigned int TA1CCR1;
extern volatile unsigned int TA1CCR2;
extern volatile unsigned int TA1IV;
extern volatile unsigned int TA1EX0;
# 5188 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int TA2CTL;
extern volatile unsigned int TA2CCTL0;
extern volatile unsigned int TA2CCTL1;
extern volatile unsigned int TA2R;
extern volatile unsigned int TA2CCR0;
extern volatile unsigned int TA2CCR1;
extern volatile unsigned int TA2IV;
extern volatile unsigned int TA2EX0;
# 5219 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int TA3CTL;
extern volatile unsigned int TA3CCTL0;
extern volatile unsigned int TA3CCTL1;
extern volatile unsigned int TA3CCTL2;
extern volatile unsigned int TA3CCTL3;
extern volatile unsigned int TA3CCTL4;
extern volatile unsigned int TA3R;
extern volatile unsigned int TA3CCR0;
extern volatile unsigned int TA3CCR1;
extern volatile unsigned int TA3CCR2;
extern volatile unsigned int TA3CCR3;
extern volatile unsigned int TA3CCR4;
extern volatile unsigned int TA3IV;
extern volatile unsigned int TA3EX0;
# 5258 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int TB0CTL;
extern volatile unsigned int TB0CCTL0;
extern volatile unsigned int TB0CCTL1;
extern volatile unsigned int TB0CCTL2;
extern volatile unsigned int TB0CCTL3;
extern volatile unsigned int TB0CCTL4;
extern volatile unsigned int TB0CCTL5;
extern volatile unsigned int TB0CCTL6;
extern volatile unsigned int TB0R;
extern volatile unsigned int TB0CCR0;
extern volatile unsigned int TB0CCR1;
extern volatile unsigned int TB0CCR2;
extern volatile unsigned int TB0CCR3;
extern volatile unsigned int TB0CCR4;
extern volatile unsigned int TB0CCR5;
extern volatile unsigned int TB0CCR6;
extern volatile unsigned int TB0EX0;
extern volatile unsigned int TB0IV;
# 5406 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int UCA0CTLW0;
extern volatile unsigned char UCA0CTLW0_L;
extern volatile unsigned char UCA0CTLW0_H;


extern volatile unsigned int UCA0CTLW1;
extern volatile unsigned char UCA0CTLW1_L;
extern volatile unsigned char UCA0CTLW1_H;
extern volatile unsigned int UCA0BRW;
extern volatile unsigned char UCA0BRW_L;
extern volatile unsigned char UCA0BRW_H;


extern volatile unsigned int UCA0MCTLW;
extern volatile unsigned char UCA0MCTLW_L;
extern volatile unsigned char UCA0MCTLW_H;
extern volatile unsigned char UCA0STATW;
extern volatile unsigned int UCA0RXBUF;
extern volatile unsigned char UCA0RXBUF_L;
extern volatile unsigned char UCA0RXBUF_H;
extern volatile unsigned int UCA0TXBUF;
extern volatile unsigned char UCA0TXBUF_L;
extern volatile unsigned char UCA0TXBUF_H;
extern volatile unsigned char UCA0ABCTL;
extern volatile unsigned int UCA0IRCTL;
extern volatile unsigned char UCA0IRCTL_L;
extern volatile unsigned char UCA0IRCTL_H;


extern volatile unsigned int UCA0IE;
extern volatile unsigned char UCA0IE_L;
extern volatile unsigned char UCA0IE_H;
extern volatile unsigned int UCA0IFG;
extern volatile unsigned char UCA0IFG_L;
extern volatile unsigned char UCA0IFG_H;
extern volatile unsigned int UCA0IV;
# 5451 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int UCA1CTLW0;
extern volatile unsigned char UCA1CTLW0_L;
extern volatile unsigned char UCA1CTLW0_H;


extern volatile unsigned int UCA1CTLW1;
extern volatile unsigned char UCA1CTLW1_L;
extern volatile unsigned char UCA1CTLW1_H;
extern volatile unsigned int UCA1BRW;
extern volatile unsigned char UCA1BRW_L;
extern volatile unsigned char UCA1BRW_H;


extern volatile unsigned int UCA1MCTLW;
extern volatile unsigned char UCA1MCTLW_L;
extern volatile unsigned char UCA1MCTLW_H;
extern volatile unsigned char UCA1STATW;
extern volatile unsigned int UCA1RXBUF;
extern volatile unsigned char UCA1RXBUF_L;
extern volatile unsigned char UCA1RXBUF_H;
extern volatile unsigned int UCA1TXBUF;
extern volatile unsigned char UCA1TXBUF_L;
extern volatile unsigned char UCA1TXBUF_H;
extern volatile unsigned char UCA1ABCTL;
extern volatile unsigned int UCA1IRCTL;
extern volatile unsigned char UCA1IRCTL_L;
extern volatile unsigned char UCA1IRCTL_H;


extern volatile unsigned int UCA1IE;
extern volatile unsigned char UCA1IE_L;
extern volatile unsigned char UCA1IE_H;
extern volatile unsigned int UCA1IFG;
extern volatile unsigned char UCA1IFG_L;
extern volatile unsigned char UCA1IFG_H;
extern volatile unsigned int UCA1IV;
# 5497 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int UCB0CTLW0;
extern volatile unsigned char UCB0CTLW0_L;
extern volatile unsigned char UCB0CTLW0_H;


extern volatile unsigned int UCB0CTLW1;
extern volatile unsigned char UCB0CTLW1_L;
extern volatile unsigned char UCB0CTLW1_H;
extern volatile unsigned int UCB0BRW;
extern volatile unsigned char UCB0BRW_L;
extern volatile unsigned char UCB0BRW_H;


extern volatile unsigned int UCB0STATW;
extern volatile unsigned char UCB0STATW_L;
extern volatile unsigned char UCB0STATW_H;


extern volatile unsigned int UCB0TBCNT;
extern volatile unsigned char UCB0TBCNT_L;
extern volatile unsigned char UCB0TBCNT_H;
extern volatile unsigned int UCB0RXBUF;
extern volatile unsigned char UCB0RXBUF_L;
extern volatile unsigned char UCB0RXBUF_H;
extern volatile unsigned int UCB0TXBUF;
extern volatile unsigned char UCB0TXBUF_L;
extern volatile unsigned char UCB0TXBUF_H;
extern volatile unsigned int UCB0I2COA0;
extern volatile unsigned char UCB0I2COA0_L;
extern volatile unsigned char UCB0I2COA0_H;
extern volatile unsigned int UCB0I2COA1;
extern volatile unsigned char UCB0I2COA1_L;
extern volatile unsigned char UCB0I2COA1_H;
extern volatile unsigned int UCB0I2COA2;
extern volatile unsigned char UCB0I2COA2_L;
extern volatile unsigned char UCB0I2COA2_H;
extern volatile unsigned int UCB0I2COA3;
extern volatile unsigned char UCB0I2COA3_L;
extern volatile unsigned char UCB0I2COA3_H;
extern volatile unsigned int UCB0ADDRX;
extern volatile unsigned char UCB0ADDRX_L;
extern volatile unsigned char UCB0ADDRX_H;
extern volatile unsigned int UCB0ADDMASK;
extern volatile unsigned char UCB0ADDMASK_L;
extern volatile unsigned char UCB0ADDMASK_H;
extern volatile unsigned int UCB0I2CSA;
extern volatile unsigned char UCB0I2CSA_L;
extern volatile unsigned char UCB0I2CSA_H;
extern volatile unsigned int UCB0IE;
extern volatile unsigned char UCB0IE_L;
extern volatile unsigned char UCB0IE_H;
extern volatile unsigned int UCB0IFG;
extern volatile unsigned char UCB0IFG_L;
extern volatile unsigned char UCB0IFG_H;
extern volatile unsigned int UCB0IV;
# 5561 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int UCB1CTLW0;
extern volatile unsigned char UCB1CTLW0_L;
extern volatile unsigned char UCB1CTLW0_H;


extern volatile unsigned int UCB1CTLW1;
extern volatile unsigned char UCB1CTLW1_L;
extern volatile unsigned char UCB1CTLW1_H;
extern volatile unsigned int UCB1BRW;
extern volatile unsigned char UCB1BRW_L;
extern volatile unsigned char UCB1BRW_H;


extern volatile unsigned int UCB1STATW;
extern volatile unsigned char UCB1STATW_L;
extern volatile unsigned char UCB1STATW_H;


extern volatile unsigned int UCB1TBCNT;
extern volatile unsigned char UCB1TBCNT_L;
extern volatile unsigned char UCB1TBCNT_H;
extern volatile unsigned int UCB1RXBUF;
extern volatile unsigned char UCB1RXBUF_L;
extern volatile unsigned char UCB1RXBUF_H;
extern volatile unsigned int UCB1TXBUF;
extern volatile unsigned char UCB1TXBUF_L;
extern volatile unsigned char UCB1TXBUF_H;
extern volatile unsigned int UCB1I2COA0;
extern volatile unsigned char UCB1I2COA0_L;
extern volatile unsigned char UCB1I2COA0_H;
extern volatile unsigned int UCB1I2COA1;
extern volatile unsigned char UCB1I2COA1_L;
extern volatile unsigned char UCB1I2COA1_H;
extern volatile unsigned int UCB1I2COA2;
extern volatile unsigned char UCB1I2COA2_L;
extern volatile unsigned char UCB1I2COA2_H;
extern volatile unsigned int UCB1I2COA3;
extern volatile unsigned char UCB1I2COA3_L;
extern volatile unsigned char UCB1I2COA3_H;
extern volatile unsigned int UCB1ADDRX;
extern volatile unsigned char UCB1ADDRX_L;
extern volatile unsigned char UCB1ADDRX_H;
extern volatile unsigned int UCB1ADDMASK;
extern volatile unsigned char UCB1ADDMASK_L;
extern volatile unsigned char UCB1ADDMASK_H;
extern volatile unsigned int UCB1I2CSA;
extern volatile unsigned char UCB1I2CSA_L;
extern volatile unsigned char UCB1I2CSA_H;
extern volatile unsigned int UCB1IE;
extern volatile unsigned char UCB1IE_L;
extern volatile unsigned char UCB1IE_H;
extern volatile unsigned int UCB1IFG;
extern volatile unsigned char UCB1IFG_L;
extern volatile unsigned char UCB1IFG_H;
extern volatile unsigned int UCB1IV;
# 6107 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430fr6989.h" 3 4
extern volatile unsigned int WDTCTL;
extern volatile unsigned char WDTCTL_L;
extern volatile unsigned char WDTCTL_H;
# 1679 "/home/y/y-study/msp430-gcc-9.3/msp430-elf/include/devices/msp430.h" 2 3 4
# 4 "led/led.c" 2


# 5 "led/led.c"
int led(void)
{

     
# 8 "led/led.c" 3 4
    (PAOUT_L) 
# 8 "led/led.c"
          |= 
# 8 "led/led.c" 3 4
             (0x0001)
# 8 "led/led.c"
                 ;
     return 0;
}
